### ISSUE TITLE
[DOCS] Mention how to properly input the CloudProxy URL

### ISSUE THREAD

**Issue by NoahCardoza** [abeloin/Jackett#1]
Hey!

I'm the author of [CloudProxy](https://github.com/NoahCardoza/CloudProxy) and someone recently joined my Discord server unable to connect CloudProxy to Jackett.

![image](https://user-images.githubusercontent.com/10343470/99654536-52fb2980-2a0f-11eb-9afc-d231ccfe535a.png)

It might be worth mentioning this in a FAQ or something since I see how this could be confusing.

I hope this is the right place to post this, if not let me know and I'll move it elsewhere.

**Comment by abeloin** [comment]
I'm not sure if there is a proper place right now, but I've made changes to the readme.md with some instructions on how to configure it.

https://github.com/abeloin/Jackett#configuring-cloudproxy-integration
