### ISSUE TITLE
Error connecting to YetAnotherCloudProxy server

### ISSUE THREAD

**Issue by ulysserevient** [abeloin/Jackett#2]
Hi,
since a week Jackett couldn't connect to flaresolverr.

`An error occurred while testing this indexer
Exception (yggtorrent): Error connecting to YetAnotherCloudProxy server: System.Net.Http.HttpRequestException: Connection refused ---> System.Net.Sockets.SocketException (111): Connection refused at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken) --- End of inner exception stack trace --- at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken) at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts) at YetAnotherCloudProxySharp.Solvers.YetAnotherCloudProxy.<>c__DisplayClass5_0.<b__0>d.MoveNext(): Error connecting to YetAnotherCloudProxy server: System.Net.Http.HttpRequestException: Connection refused ---> System.Net.Sockets.SocketException (111): Connection refused at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken) --- End of inner exception stack trace --- at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken) at System.Net.Http.HttpConne`

When trying flaresolverr, it seems it works !
Can you help me please ?

**Comment by xfouloux** [comment]
did you used the right name for connecting jackett to the proxy container ?
if your container is named : cloudproxy
then in jackett you should put 

http://cloudproxy:8191

(if they are on the same docker host that is)

**Comment by ulysserevient** [comment]
Hi,
I tried that.
Jackett end Flaresolverr are on the same docker.
Same error with flaresolverr docker name

I don't know if there is an error with jackett or flaresolverr
When i try 
` curl -L -X POST 'http://localhost:8191/v1' -H 'Content-Type: application/json' --data-raw '{
    "url":"https://www.yggtorrent.si/",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64; rv:76.0) Gecko/20100101 Firefox/76.0",
    "maxTimeout": 10000
}'`
obtain
`{"status":"error","message":"Maximum timeout reached. maxTimeout=10000 (ms)","startTimestamp":1607323726846,"endTimestamp":1607323738810,"version":"1.0.0"}`

but with google.fr
`{"status":"ok","message":"","startTimestamp":1607323840755,"endTimestamp":1607323845339,"version":"1.0.0","solution":{"url":"https://www.google.fr/","response":"<!DOCTYPE html>.................`

**Comment by LacazeThomas** [comment]
I had the same issue,  i downgrade cloudproxy from v1.0.1 to v1.0.0

**Comment by ulysserevient** [comment]
do you mean flaresolverr as cloudproxy ?

**Comment by ulysserevient** [comment]
Have you try yggtorrent actually ?
Perhaps a problem with it ...
Could you confirm thaht ygg is now working ?
Thx

**Comment by Luxumbra27** [comment]
Had a probably similar issue, but directly from Jackett like: 
`[...]
cloudproxy_1    | 2020-12-07T13:53:29.565Z INFO REQ-1 Cloudflare detected
cloudproxy_1    | 2020-12-07T13:53:29.583Z DEBUG REQ-1 Waiting for Cloudflare challenge...
cloudproxy_1    | Error: Execution context was destroyed, most likely because of a navigation.
cloudproxy_1    |     at rewriteError (/home/node/cloudproxy/node_modules/puppeteer/lib/ExecutionContext.js:146:23)
[...]`
Downgrading cloudproxy to v1.0.0 as @LacazeThomas  said made it work. 
[Here](https://registry.hub.docker.com/layers/noahcardoza/cloudproxy/v1.0.0/images/sha256-e642ac58b78fa5a18610292085f3a474d9150f4f281190c4cd72e7a5d9818ba6?context=explore)

**Comment by xfouloux** [comment]
YGG won't work for now, only YGGCookie

**Comment by ulysserevient** [comment]
YGG won't work with flaresolverr for now ?
I never made working YGGCookie !

**Comment by xfouloux** [comment]
@ulysserevient follow the recommendation mentionned by #3 
or use YGGCookies for now

**Comment by abeloin** [comment]
> Hi,
> I tried that.
> Jackett end Flaresolverr are on the same docker.
> Same error with flaresolverr docker name
> 
> I don't know if there is an error with jackett or flaresolverr
> When i try
> ` curl -L -X POST 'http://localhost:8191/v1' -H 'Content-Type: application/json' --data-raw '{ "url":"https://www.yggtorrent.si/", "userAgent": "Mozilla/5.0 (X11; Linux x86_64; rv:76.0) Gecko/20100101 Firefox/76.0", "maxTimeout": 10000 }'`
> obtain
> `{"status":"error","message":"Maximum timeout reached. maxTimeout=10000 (ms)","startTimestamp":1607323726846,"endTimestamp":1607323738810,"version":"1.0.0"}`
> 
> but with google.fr
> `{"status":"ok","message":"","startTimestamp":1607323840755,"endTimestamp":1607323845339,"version":"1.0.0","solution":{"url":"https://www.google.fr/","response":"<!DOCTYPE html>.................`

Try to put a maxTimeout of at least 60000 (60 sec), 10 seconds is definitely not enough.

The Jackett build that I provide doesn't work with Flaresolverr anymore since it wasn't working properly.

It will only work with CloudProxy:

- https://github.com/NoahCardoza/CloudProxy
- https://registry.hub.docker.com/r/noahcardoza/cloudproxy

You should use Cloudproxy at least version 1.1.0 which fix a important bug:

**Comment by abeloin** [comment]
> Had a probably similar issue, but directly from Jackett like:
> `[...] cloudproxy_1 | 2020-12-07T13:53:29.565Z INFO REQ-1 Cloudflare detected cloudproxy_1 | 2020-12-07T13:53:29.583Z DEBUG REQ-1 Waiting for Cloudflare challenge... cloudproxy_1 | Error: Execution context was destroyed, most likely because of a navigation. cloudproxy_1 | at rewriteError (/home/node/cloudproxy/node_modules/puppeteer/lib/ExecutionContext.js:146:23) [...] `
> Downgrading cloudproxy to v1.0.0 as @LacazeThomas said made it work.
> [Here](https://registry.hub.docker.com/layers/noahcardoza/cloudproxy/v1.0.0/images/sha256-e642ac58b78fa5a18610292085f3a474d9150f4f281190c4cd72e7a5d9818ba6?context=explore)

This bug is fixed in version 1.1.0 of CloudProxy. It was present in version 1.0.0 and 1.0.1 but didn't appear often.

**Comment by xfouloux** [comment]
Absolutely i wasn't using the latest too and now that i updated my container to latest cloudproxy version i don't have any issue with YGG or YGGCookies

**Comment by xfouloux** [comment]
well back on my comments, now i can't make YGGCookie work, only YGGTorrent
Strange things =p !

**Comment by FlavienMedina** [comment]
> well back on my comments, now i can't make YGGCookie work, only YGGTorrent
> Strange things =p !

How you do that please ?

**Comment by xfouloux** [comment]
well just use the other indexer, YGGTorrent, instead of YGGCookie

**Comment by FlavienMedina** [comment]
> well just use the other indexer, YGGTorrent, instead of YGGCookie

Ok but me i have this error :
The cookies provided by YetAnotherCloudProxy are not valid

**Comment by abeloin** [comment]
@FlavienMedina You should have more info after that message indicating the issue. Also there was a bug in the recent version which is fixed in 0.117.9.

Also Jackett is now officially supporting it via Flaresolverr starting with 0.17.50

**Comment by abeloin** [comment]
Official version available:
Replace images path by the one provided with
https://github.com/Jackett/Jackett
https://github.com/FlareSolverr/FlareSolverr
