### ISSUE TITLE
flaresolverr: [yggtorrent] Maximum timeout reached. maxTimeout=60000 (ms) (Config)

### ISSUE THREAD

**Issue by hexleyOlive** [abeloin/Jackett#3]
Hi,

I try to use the Jackett release with the CloudProxy API Url feature.

### Environment

**OS**: Synology DS918+ - DSM 6.2.3-25426 Update 2
**.Net Runtime**: MONO 5.20.1.34-16
**Jackett Version**: Version 0.116.19.0

Jackett run under docker container : [sclemenceau-docker-jackett](https://registry.hub.docker.com/r/sclemenceau/docker-jackett/)

Flaresolverr run under docker container : [zhuxiaole1992/flaresolverr](https://registry.hub.docker.com/r/zhuxiaole1992/flaresolverr/)

### Description

Add yggtorrent indexer return an error:
An error occurred while updating this indexer
Maximum timeout reached. maxTimeout=60000 (ms)

The Flaresolverr seems to be available and answer correctly, a simple call with the Flaresolverr URL set in Jackett give me the result below:
{"status":"error","message":"Body must be in JSON format","startTimestamp":1607423031696,"endTimestamp":1607423031697,"version":"1.0.0"}

Can you help me to understand why this error happens?
Thanks !

### Logged Error Messages

`YetAnotherCloudProxySharp.Exceptions.YetAnotherCloudProxyException: Maximum timeout reached. maxTimeout=60000 (ms)    at YetAnotherCloudProxySharp.Solvers.YetAnotherCloudProxy.<>c__DisplayClass5_0.<<Solve>b__0>d.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at YetAnotherCloudProxySharp.Utilities.SemaphoreLocker.LockAsync[T](Func`1 worker)    at YetAnotherCloudProxySharp.Solvers.YetAnotherCloudProxy.Solve(HttpRequestMessage request)    at YetAnotherCloudProxySharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)    at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)    at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 166    at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 184    at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 495    at Jackett.Common.Indexers.CardigannIndexer.GetConfigurationForSetup(Boolean automaticlogin) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 840    at Jackett.Common.Indexers.CardigannIndexer.DoLogin() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 512    at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 917    at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 94    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited\|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited\|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited\|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited\|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited\|17_0(ResourceInvoker invoker, Task task, IDisposable scope)    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask\|6_0(Endpoint endpoint, Task requestTask, ILogger logger)    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
`

Exception in GetConfigurationForSetup (yggtorrent): YetAnotherCloudProxySharp.Exceptions.YetAnotherCloudProxyException: Maximum timeout reached. maxTimeout=60000 (ms)
   at YetAnotherCloudProxySharp.Solvers.YetAnotherCloudProxy.<>c__DisplayClass5_0.<<Solve>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at YetAnotherCloudProxySharp.Utilities.SemaphoreLocker.LockAsync[T](Func`1 worker)
   at YetAnotherCloudProxySharp.Solvers.YetAnotherCloudProxy.Solve(HttpRequestMessage request)
   at YetAnotherCloudProxySharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 166
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 184
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 495
   at Jackett.Common.Indexers.CardigannIndexer.GetConfigurationForSetup(Boolean automaticlogin) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 840
   at Jackett.Common.Indexers.CardigannIndexer.GetConfigurationForSetup() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 819

**Comment by hexleyOlive** [comment]
Solved, as mentioned here #2, Downgrading cloudproxy to v1.0.0 as @LacazeThomas said made it work.
[Here](https://registry.hub.docker.com/layers/noahcardoza/cloudproxy/v1.0.0/images/sha256-e642ac58b78fa5a18610292085f3a474d9150f4f281190c4cd72e7a5d9818ba6?context=explore)

**Comment by abeloin** [comment]
@hexleyOlive Flaresolverr isn't supported by my build of Jackett since it wasn't working anymore.

Please use Cloudproxy and use version => 1.1.0 since it fix a major bug.

https://registry.hub.docker.com/r/noahcardoza/cloudproxy

**Comment by hexleyOlive** [comment]
Hi,

Thanks for your answer.
As mentioned in my last post, solution was to move on cloudproxy v1.0.0.

FYI, I tried to upgrade from 1.0.0 to 1.1.0, but it doesn't work.
Below example of errors with yggtorent indexer + cloudproxy 1.1.0.

Jackett.Common.IndexerException: Exception (yggtorrent): The cookies provided by YetAnotherCloudProxy are not valid
 ---> System.Exception: Parse error

Error on 20201210083757 for YGGtorrent.txtYetAnotherCloudProxySharp.Exceptions.YetAnotherCloudProxyException: The cookies provided by YetAnotherCloudProxy are not valid
   at YetAnotherCloudProxySharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)

Downgrade cloudproxy to 1.0.0 solve the problem.
Don't know which major bug is fixed in cloudproxy 1.1.0 but not this one ;)

**Comment by abeloin** [comment]
Hello,

Can you check cloudproxy's logs when the error happen with 1.1.0? You should have something like this:

```
2020-12-10T16:55:05.261Z INFO REQ-2 Incoming request: POST /v1
2020-12-10T16:55:05.261Z INFO REQ-2 Params: {"headers":null,"maxTimeout":60000,"cmd":"request.get","url":"https://www2.yggtorrent.si/","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36"}
2020-12-10T16:55:05.261Z DEBUG REQ-2 Launching headless browser...
2020-12-10T16:55:05.573Z DEBUG REQ-2 Using custom UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36
2020-12-10T16:55:05.575Z DEBUG REQ-2 Adding custom headers: {}
2020-12-10T16:55:05.575Z DEBUG REQ-2 { headers: [Function (anonymous)] }
2020-12-10T16:55:05.576Z DEBUG REQ-2 Navigating to... https://www2.yggtorrent.si/
2020-12-10T16:55:06.133Z DEBUG REQ-2 {
  headers: {
    'upgrade-insecure-requests': '1',
    'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36'
  }
}
2020-12-10T16:55:06.344Z INFO REQ-2 Cloudflare detected
2020-12-10T16:55:06.382Z DEBUG REQ-2 Waiting for Cloudflare challenge...
2020-12-10T16:55:11.777Z DEBUG REQ-2 Validating HTML code...
2020-12-10T16:55:11.834Z INFO REQ-2 Successful response in 6.573 s
```

The bug fixed 1.1.0 was about the container using more and more cpu and memory because chrome processes were not closed properly.

**Comment by hexleyOlive** [comment]
Hi,
I use cloudproxy's in a docker container on a NAS Synology.
Can you give me the good way to extract log required?

Thanks

**Comment by abeloin** [comment]
This might be useful

> Go to the Container page, select the container and click Details to check logs from the Log tab

From: https://www.synology.com/en-us/knowledgebase/DSM/tutorial/Virtualization/How_can_I_debug_and_fix_common_Docker_container_issues

Or have a look at the section: Manage Containers - To get more details about each container - Log:
https://www.synology.com/en-global/knowledgebase/DSM/help/Docker/Docker

**Comment by hexleyOlive** [comment]
Hi,

Thanks for tips about logs.
Find enclosed log for my container cloudproxy 1.1.0.
The error reported was this morning, maybe can you find something in log about this one.
FYI : I try again few minutes ago, I'm not able to reproduce the problem now… strange.
I keep now cloudproxy 1.1.0 enabled and back you if the same error happens again.
Thanks

**Comment by abeloin** [comment]
Official version available:
Replace images path by the one provided with
https://github.com/Jackett/Jackett
https://github.com/FlareSolverr/FlareSolverr
